name: inner link check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - uses: actions/checkout@v2
    - name: check
      run: |
        python3 .github/workflows/script/link_check.py --check-inner-link 2>&1 >/dev/null | curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "failed link check: ${{ github.sha }}",
          "body": &1
          }'
